@startuml
participant Actor
Actor -> AddNewModuleCommand : executeCommand
activate AddNewModuleCommand
AddNewModuleCommand -> ModuleStorage : getSem
activate ModuleStorage
ModuleStorage --> AddNewModuleCommand
deactivate ModuleStorage
AddNewModuleCommand -> ModuleData : new
activate ModuleData
ModuleData --> AddNewModuleCommand
deactivate ModuleData
AddNewModuleCommand -> AddNewModuleCommand : checkGradeFormat
activate AddNewModuleCommand
AddNewModuleCommand -> ModuleList : gradesToPoints
activate ModuleList
ModuleList -> InvalidGradeException : new
activate InvalidGradeException
InvalidGradeException --> ModuleList
deactivate InvalidGradeException
ModuleList --> AddNewModuleCommand
deactivate ModuleList
AddNewModuleCommand --> AddNewModuleCommand
deactivate AddNewModuleCommand
AddNewModuleCommand -> AddNewModuleCommand : checkMcFormat
activate AddNewModuleCommand
AddNewModuleCommand --> AddNewModuleCommand
deactivate AddNewModuleCommand
AddNewModuleCommand -> WrongModuleFormatException : new
activate WrongModuleFormatException
WrongModuleFormatException --> AddNewModuleCommand
deactivate WrongModuleFormatException
AddNewModuleCommand -> AddNewModuleCommand : checkIfModuleExists
activate AddNewModuleCommand
AddNewModuleCommand -> ModuleList : size
activate ModuleList
ModuleList --> AddNewModuleCommand
deactivate ModuleList
AddNewModuleCommand --> AddNewModuleCommand
deactivate AddNewModuleCommand
AddNewModuleCommand -> ModuleList : add
activate ModuleList
ModuleList --> AddNewModuleCommand
deactivate ModuleList
AddNewModuleCommand -> UiText : confirmModuleUpdate
activate UiText
UiText --> AddNewModuleCommand
deactivate UiText
AddNewModuleCommand -> AddNewModuleCommand : saveToStorage
activate AddNewModuleCommand
AddNewModuleCommand -> ModuleStorage : writeToFile
activate ModuleStorage
ModuleStorage -> ModuleList : printString
activate ModuleList
ModuleList -> ModuleData : fileFormat
activate ModuleData
ModuleData --> ModuleList
deactivate ModuleData
ModuleList --> ModuleStorage
deactivate ModuleList
ModuleStorage --> AddNewModuleCommand
deactivate ModuleStorage
AddNewModuleCommand -> ModuleStorage : fileDoesntExist
activate ModuleStorage
ModuleStorage --> AddNewModuleCommand
deactivate ModuleStorage
AddNewModuleCommand --> AddNewModuleCommand
deactivate AddNewModuleCommand
AddNewModuleCommand -> UiText : moduleAlreadyExists
activate UiText
UiText --> AddNewModuleCommand
deactivate UiText
AddNewModuleCommand -> UiText : separationLine
activate UiText
UiText --> AddNewModuleCommand
deactivate UiText
return
@enduml