@startuml
'https://plantuml.com/sequence-diagram

hide footbox
title addStore

-> ":addStore" :
activate ":addStore"
":addStore" -> ":FoodStoreUi" : addStore
activate ":FoodStoreUi"
":FoodStoreUi" -> ":FoodStoreUi" : showToUser
":FoodStoreUi" --> ":addStore"
deactivate ":FoodStoreUi"
":addStore" -> ":FoodStoreList" : add
activate ":FoodStoreList"
":FoodStoreList" --> ":addStore"
deactivate ":FoodStoreList"
return

@enduml